import { useEffect, useMemo, useState, type FormEvent } from 'react'
import './App.css'

type Report = {
  address: string; zone: string; zoneDescription: string; overlays: string; lga: string
  dwellings: string; storeys: string; parking: string; parkingOther: string; existing: string
  siteArea: string; frontage: string; frontageStreet: string; summary: string
  siteCoverage: string; permeable: string; gardenArea: string; gardenRequirement: string; canopy: string; maxHeight: string
  ordinance: string; images: { satellite: string; satelliteBoundary: string; zoning: string; overlays: string[] }
  openSpace: { secluded: string; total: string }[]
}

const blankReport: Report = { address: '', zone: '', zoneDescription: '', overlays: '', lga: '', dwellings: '2', storeys: '2', parking: 'Onsite parking', parkingOther: '', existing: 'Single storey dwelling', siteArea: '', frontage: '', frontageStreet: '', summary: '', siteCoverage: '', permeable: '', gardenArea: '', gardenRequirement: '', canopy: '', maxHeight: '', ordinance: '', images: { satellite: '', satelliteBoundary: '', zoning: '', overlays: [] }, openSpace: [] }
const steps = ['Project address', 'Zone & overlays', 'Development', 'Existing site', 'Site area', 'Frontage', 'Frontage street', 'Aerial context', 'Zoning map', 'Overlay maps', 'Site coverage', 'Permeable area', 'Garden area', 'Canopy area', 'Development summary', 'Private open space', 'Zone standards', 'Building height', 'Garden requirement']
const sample = { zone: 'GRZ1', zoneDescription: 'General Residential Zone - Schedule 1', overlays: 'DDO18 — Design and Development Overlay', lga: 'MELBOURNE' }
const api = async (path: string, options: RequestInit = {}) => { const response = await fetch(path, { credentials: 'include', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options }); const payload = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(payload?.error || 'Request failed'); return payload }

function App() {
  const [view, setView] = useState<'home' | 'wizard' | 'report'>('home')
  const [step, setStep] = useState(() => Math.min(Math.max(Number(localStorage.getItem('planning-report-step') || 0), 0), steps.length - 1))
  const [report, setReport] = useState<Report>(() => JSON.parse(localStorage.getItem('planning-report') || JSON.stringify(blankReport)))
  const [user, setUser] = useState<{ id: string; name: string; email: string } | null>(null)
  const [authOpen, setAuthOpen] = useState(false)
  const [authMode, setAuthMode] = useState<'login' | 'register'>('login')
  const [projectId, setProjectId] = useState<string | null>(null)
  const [lookupState, setLookupState] = useState('Ready to look up')
  const [saved, setSaved] = useState(false)

  const update = (key: keyof Report, value: any) => setReport((current) => ({ ...current, [key]: value }))
  useEffect(() => { api('/api/auth/me').then((result) => setUser(result.user)).catch(() => undefined) }, [])
  const save = async () => { localStorage.setItem('planning-report', JSON.stringify(report)); localStorage.setItem('planning-report-step', String(step)); try { const result = projectId ? await api(`/api/projects/${projectId}`, { method: 'PUT', body: JSON.stringify({ name: report.address, report }) }) : await api('/api/projects', { method: 'POST', body: JSON.stringify({ name: report.address, report }) }); setProjectId(result.project.id) } catch { /* Local drafts remain available when signed out or the API is offline. */ } setSaved(true); setTimeout(() => setSaved(false), 1800) }
  const goToStep = (nextStep: number) => { const safeStep = Math.min(Math.max(nextStep, 0), steps.length - 1); setStep(safeStep); localStorage.setItem('planning-report-step', String(safeStep)) }
  const start = () => { setView('wizard'); setReport((current) => current.address ? current : { ...blankReport }); goToStep(report.address ? step : 0) }
  const dwellings = Math.max(1, Number(report.dwellings) || 1)
  const calculatedGardenRequirement = report.siteArea && Number(report.siteArea) > 650 ? 35 : report.siteArea && Number(report.siteArea) > 500 ? 30 : report.siteArea && Number(report.siteArea) >= 400 ? 25 : 0
  const gardenRequirement = report.gardenRequirement !== undefined && report.gardenRequirement !== '' ? Number(report.gardenRequirement) : calculatedGardenRequirement
  const gardenClause = getGardenClause(report.zone)
  const gardenAchieved = report.siteArea && report.gardenArea ? Math.round((Number(report.gardenArea) / Number(report.siteArea)) * 100) : 0
  const standard = report.ordinance || (dwellings > 1 ? 'B1 — Minimum street setback: 9m\nB2 — Minimum side setback: 1m\nB3 — Maximum site coverage: 60%' : 'A1 — Minimum street setback: 9m\nA2 — Minimum side setback: 1m\nA3 — Maximum site coverage: 60%')

  const title = useMemo(() => report.address || 'Untitled planning report', [report.address])

  const authenticate = async (mode: 'login' | 'register', fields: { name: string; email: string; password: string }) => { const result = await api(`/api/auth/${mode}`, { method: 'POST', body: JSON.stringify(fields) }); setUser(result.user); setAuthOpen(false) }
  if (view === 'report') return <ReportView report={report} title={title} standard={standard} gardenRequirement={gardenRequirement} gardenAchieved={gardenAchieved} gardenClause={gardenClause} onBack={() => setView('wizard')} />
  return <div className="app-shell">
    <header className="topbar"><button className="brand" onClick={() => setView('home')}><span className="brand-mark">◒</span><span>PLAN / VIC</span></button><div className="top-actions"><span className="saved-note">{saved ? 'Draft saved' : 'Victoria planning workspace'}</span><button className="avatar" onClick={() => user ? api('/api/auth/logout').then(() => setUser(null)) : setAuthOpen(true)}>{user ? user.name.slice(0, 2).toUpperCase() : 'JD'}</button></div></header>
    {view === 'home' ? <Home onStart={start} onLogin={() => setAuthOpen(true)} loggedIn={Boolean(user)} report={report} /> : <Wizard step={step} setStep={goToStep} report={report} update={update} save={save} saved={saved} lookupState={lookupState} setLookupState={setLookupState} onComplete={() => { save(); setView('report') }} onCancel={() => setView('home')} standard={standard} dwellings={dwellings} gardenRequirement={gardenRequirement} gardenAchieved={gardenAchieved} gardenClause={gardenClause} user={user} onLogin={() => setAuthOpen(true)} />}
    {authOpen && <AuthPanel mode={authMode} setMode={setAuthMode} onClose={() => setAuthOpen(false)} onSubmit={authenticate} />}
  </div>
}

function Home({ onStart, onLogin, loggedIn, report }: { onStart: () => void; onLogin: () => void; loggedIn: boolean; report: Report }) {
  return <main className="home"><section className="hero"><div className="eyebrow">VICTORIA / RESIDENTIAL DEVELOPMENT</div><h1>Planning reports,<br /><em>made legible.</em></h1><p>Build a clear, evidence-led town planning report from site facts to final schedule in one guided workspace.</p><div className="hero-actions"><button className="primary" onClick={onStart}>Create project <span>↗</span></button><button className="text-button" onClick={onLogin}>{loggedIn ? 'Signed in as Jordan' : 'Sign in to save projects'} <span>→</span></button></div></section><section className="project-area"><div className="section-heading"><div><span className="eyebrow">YOUR WORKSPACE</span><h2>Recent projects</h2></div><span className="project-count">01 / 01</span></div><article className="project-card" onClick={onStart}><div className="project-icon">⌂</div><div className="project-info"><h3>{report.address || 'Start your first project'}</h3><p>{report.address ? 'Draft report · Updated just now' : 'A guided 19-step workflow for your next application'}</p></div><span className="project-arrow">→</span></article><div className="workspace-foot"><span>Vicmap connected</span><span className="dot"></span><span>Drafts autosave locally</span><a href="#documentation">Read documentation ↗</a></div></section></main>
}

function Wizard({ step, setStep, report, update, save, saved, lookupState, setLookupState, onComplete, onCancel, standard, dwellings, gardenRequirement, gardenAchieved, gardenClause }: any) {
  const isLast = step === steps.length - 1
  const [standardsState, setStandardsState] = useState('Ready to scrape')
  const lookup = async () => { setLookupState('Querying Vicmap…'); try { const result = await api(`/api/vicmap/lookup?address=${encodeURIComponent(report.address)}`); const parcel = result.parcel; if (parcel.zone) update('zone', parcel.zone); if (parcel.zoneDescription) update('zoneDescription', parcel.zoneDescription); if (parcel.overlays) update('overlays', parcel.overlays); if (parcel.lga) update('lga', parcel.lga); if (parcel.siteArea) update('siteArea', String(Math.round(Number(parcel.siteArea)))); if (result.maps) update('images', { satellite: result.maps.satellite || '', satelliteBoundary: result.maps.satelliteBoundary || '', zoning: result.maps.zoning || '', overlays: result.maps.overlays || [] }); if (!report.frontageStreet) update('frontageStreet', formatStreetName(report.address)); setLookupState(result.planningControlsAvailable ? 'Vicmap match found' : 'Parcel found — enter zone manually') } catch { setReportDefaults(report, update); setLookupState('Vicmap unavailable — edit manually') } }
  const scrapeStandards = async () => { setStandardsState('Scraping planning scheme…'); try { const result = await api(`/api/planning/standards?lga=${encodeURIComponent(report.lga)}&zone=${encodeURIComponent(report.zone)}&dwellings=${dwellings}`); if (result.text) update('ordinance', result.text); setStandardsState(result.message) } catch (error) { setStandardsState(error instanceof Error ? error.message : 'Scrape failed — enter manually') } }
  return <main className="wizard"><aside className="stepper"><div className="eyebrow">NEW PROJECT</div><h2>Report builder</h2><div className="step-list">{steps.map((name, index) => <button key={name} className={index === step ? 'active' : index < step ? 'complete' : ''} onClick={() => index <= step && setStep(index)}><span>{index < step ? '✓' : String(index + 1).padStart(2, '0')}</span>{name}</button>)}</div><div className="step-footer"><span className="dot green"></span>All changes saved locally</div></aside><section className="form-pane"><div className="form-top"><button className="back-link" onClick={onCancel}>← Projects</button><span>Step {String(step + 1).padStart(2, '0')} of {steps.length}</span></div><div className="form-content"><div className="eyebrow">{String(step + 1).padStart(2, '0')} / {steps.length}</div><h1>{steps[step]}</h1><p className="step-intro">{step === 0 ? 'Start with the site address. We will use it to find the parcel and planning controls.' : 'Capture the site detail that will anchor this report.'}</p><StepContent step={step} report={report} update={update} lookup={lookup} lookupState={lookupState} standard={standard} dwellings={dwellings} gardenRequirement={gardenRequirement} gardenAchieved={gardenAchieved} gardenClause={gardenClause} standardsState={standardsState} scrapeStandards={scrapeStandards} /><div className="form-nav"><button className="secondary" onClick={async () => { await save(); onCancel() }}>Save & exit</button><span>{saved ? 'Saved' : 'You can return to this draft anytime'}</span><button className="primary" onClick={() => isLast ? onComplete() : setStep(step + 1)}>{isLast ? 'Complete report' : 'Continue'} <span>→</span></button></div></div></section></main>
}

function setReportDefaults(report: Report, update: (key: keyof Report, value: string) => void) { if (!report.zone) update('zone', sample.zone); if (!report.zoneDescription) update('zoneDescription', sample.zoneDescription); if (!report.overlays) update('overlays', sample.overlays); if (!report.lga) update('lga', sample.lga); if (!report.siteArea) update('siteArea', '612'); if (!report.frontageStreet) update('frontageStreet', formatStreetName(report.address)) }

function formatStreetName(address: string) { return (address.split(',')[0] || '').replace(/^\s*\d+[A-Za-z]?\s+/, '').trim().toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase()) || 'Main Street' }
function getGardenClause(zone: string) { const prefix = zone.trim().toUpperCase(); if (prefix.startsWith('GRZ')) return '32.08'; if (prefix.startsWith('NRZ')) return '32.09'; if (prefix.startsWith('RGZ')) return '32.07'; return 'the applicable zone schedule' }

function Field({ label, value, onChange, placeholder, type = 'text', hint }: any) { return <label className="field"><span>{label}</span><input type={type} value={value || ''} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} />{hint && <small>{hint}</small>}</label> }
function Options({ value, onChange, options }: any) { return <div className="options">{options.map((option: string) => <button type="button" key={option} className={value === option ? 'selected' : ''} onClick={() => onChange(option)}><span className="radio"></span>{option}</button>)}</div> }
function OverlayFields({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  const fields = value ? value.split(/\r?\n/).map((overlay) => overlay.trim()) : ['']
  const overlays = fields.filter(Boolean)
  const updateOverlay = (index: number, nextValue: string) => onChange(fields.map((overlay, fieldIndex) => fieldIndex === index ? nextValue : overlay).join('\n'))
  const removeOverlay = (index: number) => onChange(fields.filter((_, fieldIndex) => fieldIndex !== index).join('\n'))
  return <div className="overlay-fields"><div className="overlay-heading"><span className="group-label">Overlay(s)</span><span className="overlay-count">{overlays.length} found</span></div>{fields.map((overlay, index) => <div className="overlay-row" key={index}><Field label={`Overlay ${index + 1}`} value={overlay} onChange={(nextValue: string) => updateOverlay(index, nextValue)} placeholder="e.g. LSIO — Land Subject to Inundation Overlay" />{fields.length > 1 && <button type="button" className="remove-overlay" aria-label={`Remove overlay ${index + 1}`} onClick={() => removeOverlay(index)}>×</button>}</div>)}<button type="button" className="add-overlay" onClick={() => onChange([...fields, ''].join('\n'))}>＋ Add overlay</button></div>
}
function StepContent({ step, report, update, lookup, lookupState, standard, dwellings, gardenRequirement, gardenAchieved, gardenClause, standardsState, scrapeStandards }: any) {
  if (step === 0) return <div className="stack"><Field label="Project address" value={report.address} onChange={(v: string) => update('address', v)} placeholder="12 Example Street, Carlton VIC 3053" hint="Use the street address for the parcel you are assessing." /><button className="lookup" onClick={lookup}>⌕ {lookupState}</button></div>
  if (step === 1) return <div className="stack"><div className="data-card"><span className="data-label">VICMAP RESULT / {report.lga || 'AWAITING LOOKUP'}</span><Field label="Zone code" value={report.zone} onChange={(v: string) => update('zone', v)} placeholder="GRZ1" /><Field label="Zone description" value={report.zoneDescription} onChange={(v: string) => update('zoneDescription', v)} placeholder="General Residential Zone" /><OverlayFields value={report.overlays} onChange={(v: string) => update('overlays', v)} /></div><p className="question">Does this look right? Edit any field if the Vicmap result needs correcting.</p></div>
  if (step === 2) return <div className="stack"><Field label="Proposed dwellings" value={report.dwellings} onChange={(v: string) => update('dwellings', v)} type="number" placeholder="2" /><Field label="Development storeys" value={report.storeys} onChange={(v: string) => update('storeys', v)} type="number" placeholder="2" /><span className="group-label">Parking arrangement</span><Options value={report.parking} onChange={(v: string) => update('parking', v)} options={['Onsite parking', 'No onsite parking', 'Other']} />{report.parking === 'Other' && <Field label="Describe parking arrangement" value={report.parkingOther} onChange={(v: string) => update('parkingOther', v)} placeholder="e.g. Car stacker system" />}</div>
  if (step === 3) return <Options value={report.existing} onChange={(v: string) => update('existing', v)} options={['Single storey dwelling', 'Double storey dwelling', 'Vacant']} />
  if (step === 4) return <div className="stack"><Field label="Site area" value={report.siteArea} onChange={(v: string) => update('siteArea', v)} type="number" placeholder="612" hint="Square metres (m²)" /><SiteAreaMap report={report} /><p className="question">The red boundary shows the parcel used for the site area calculation. You can replace the area above if required.</p></div>
  if (step === 5) return <Field label="Site frontage" value={report.frontage} onChange={(v: string) => update('frontage', v)} type="number" placeholder="15.2" hint="Metres" />
  if (step === 6) { const extractedStreet = formatStreetName(report.address); return <div className="stack"><Field label="Frontage presents to" value={report.frontageStreet || extractedStreet} onChange={(v: string) => update('frontageStreet', v)} placeholder="Example Street" hint="Street number removed and each word capitalised from the project address. Edit the field if the frontage is a different street." /></div> }
  if (step === 7) return <ImagePanel type="satellite" label="Satellite context" report={report} update={update} />
  if (step === 8) return <ImagePanel type="zoning" label="Zoning map" report={report} update={update} />
  if (step === 9) return <ImagePanel type="overlay" label="Overlay map" report={report} update={update} />
  if (step === 10) return <Field label="Site coverage" value={report.siteCoverage} onChange={(v: string) => update('siteCoverage', v)} type="number" placeholder="320" hint="Square metres (m²)" />
  if (step === 11) return <Field label="Permeable area" value={report.permeable} onChange={(v: string) => update('permeable', v)} type="number" placeholder="145" hint="Square metres (m²)" />
  if (step === 12) return <Field label="Garden area" value={report.gardenArea} onChange={(v: string) => update('gardenArea', v)} type="number" placeholder="190" hint="Square metres (m²)" />
  if (step === 13) return <Field label="Canopy area" value={report.canopy} onChange={(v: string) => update('canopy', v)} type="number" placeholder="42" hint="Square metres (m²)" />
  if (step === 14) return <label className="field"><span>Development summary</span><textarea value={report.summary} onChange={(e) => update('summary', e.target.value)} placeholder="Describe the proposed development, built form, landscape response and key site outcomes in approximately 70 words." rows={7}></textarea><small>{report.summary.split(/\s+/).filter(Boolean).length} / 70 words</small></label>
  if (step === 15) return <div className="stack">{Array.from({ length: dwellings }, (_, index) => { const space = report.openSpace[index] || { secluded: '', total: '' }; return <div className="data-card space-card" key={index}><span className="data-label">DWELLING {index + 1}</span><Field label="Secluded private open space" value={space.secluded} onChange={(v: string) => { const next = [...report.openSpace]; next[index] = { ...space, secluded: v }; update('openSpace', next as any) }} type="number" placeholder="25" hint="Square metres (m²)" /><Field label="Total private open space" value={space.total} onChange={(v: string) => { const next = [...report.openSpace]; next[index] = { ...space, total: v }; update('openSpace', next as any) }} type="number" placeholder="40" hint="Square metres (m²)" /></div> })}</div>
  if (step === 16) return <div className="stack"><div className="data-card"><span className="data-label">ORDINANCE / {report.zone || 'ZONE'}</span><textarea value={report.ordinance} onChange={(e) => update('ordinance', e.target.value)} placeholder={standard} rows={6}></textarea><small>Values starting with {dwellings > 1 ? 'B' : 'A'} are scraped from the Standard column for {report.zone || 'this zone'}.</small><button type="button" className="lookup" onClick={scrapeStandards}>⌕ {standardsState}</button></div><p className="question">Review the scraped standards above. Edit the table data manually if it is not correct.</p></div>
  if (step === 17) return <Field label="Maximum building height" value={report.maxHeight} onChange={(v: string) => update('maxHeight', v)} placeholder="e.g. 9m or None specified" hint="Check the zone schedule and enter 'None specified' where applicable." />
  return <div className="requirement"><label className="metric editable-metric"><span>Minimum garden area requirement</span><div className="percentage-input"><input type="number" min="0" max="100" value={report.gardenRequirement !== undefined && report.gardenRequirement !== '' ? report.gardenRequirement : gardenRequirement || ''} onChange={(event) => update('gardenRequirement', event.target.value)} /><b>%</b></div></label><div className="metric"><strong>{gardenAchieved || '—'}%</strong><span>Achieved garden area</span></div><p>Based on a site area of <b>{report.siteArea || '—'} m²</b>, the minimum requirement is calculated under Clause {gardenClause}. Edit the percentage above if the schedule or site circumstances require a correction.</p></div>
}

function ImagePanel({ type, label, report, update }: any) { const isOverlay = type === 'overlay'; const isSatellite = type === 'satellite'; const isPlanningLayer = type === 'zoning' || isOverlay; const sources = isOverlay ? (report.images.overlays.length ? report.images.overlays : ['']) : [report.images[type] || '']; const replaceImage = (index: number, file: File) => { const imageUrl = URL.createObjectURL(file); if (isOverlay) update('images', { ...report.images, overlays: report.images.overlays.map((source: string, imageIndex: number) => imageIndex === index ? imageUrl : source) }); else update('images', { ...report.images, [type]: imageUrl }); }; return <div className="stack">{sources.map((source: string, index: number) => <div className="image-panel" key={`${type}-${index}`}><div className={`map-card ${source ? 'has-image' : `visual-${type}`}`}>{isPlanningLayer && report.images.satellite && <img className="map-image map-base" src={report.images.satellite} alt="Satellite context" />}{source ? <img className={`map-image ${isPlanningLayer ? 'map-layer' : ''}`} src={source} alt={`${label} map ${index + 1}`} /> : <><div className="map-grid"></div><div className="map-pin">+</div></>}{isSatellite && report.images.satelliteBoundary && <img className="map-boundary" src={report.images.satelliteBoundary} alt="Parcel boundary overlay" />}<span className="map-caption">{label.toUpperCase()} {isOverlay ? `${index + 1} / ` : ''}/ 200M CONTEXT</span></div><p className="question">Review the generated image. Replace it if the context is incorrect.</p><label className="upload">＋ Replace with your own image<input type="file" accept="image/*" onChange={(e) => { if (e.target.files?.[0]) replaceImage(index, e.target.files[0]) }} /></label></div>)}</div> }
function SiteAreaMap({ report }: any) { const satellite = report.images.satellite; const boundary = report.images.satelliteBoundary; return <div className={`map-card site-area-map ${satellite ? 'has-image' : 'visual-satellite'}`}>{satellite ? <img className="map-image" src={satellite} alt="Satellite image of the site" /> : <><div className="map-grid"></div><div className="map-pin">+</div></>}{boundary && <img className="map-boundary" src={boundary} alt="Parcel boundary overlay" />}<span className="map-caption">SITE PARCEL / SATELLITE CONTEXT</span><span className="area-badge">{report.siteArea ? `${report.siteArea} m²` : 'Awaiting lookup'}</span></div> }

function AuthPanel({ mode, setMode, onClose, onSubmit }: { mode: 'login' | 'register'; setMode: (mode: 'login' | 'register') => void; onClose: () => void; onSubmit: (mode: 'login' | 'register', fields: { name: string; email: string; password: string }) => Promise<void> }) {
  const [fields, setFields] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await onSubmit(mode, fields) } catch (submissionError) { setError(submissionError instanceof Error ? submissionError.message : 'Unable to authenticate') } finally { setBusy(false) } }
  return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><form className="auth-panel" onSubmit={submit}><button type="button" className="modal-close" onClick={onClose}>×</button><div className="eyebrow">PLAN / VIC ACCOUNT</div><h2>{mode === 'login' ? 'Welcome back.' : 'Create your account.'}</h2><p>{mode === 'login' ? 'Sign in to sync projects across devices.' : 'Keep your planning drafts safe and accessible.'}</p>{mode === 'register' && <Field label="Name" value={fields.name} onChange={(value: string) => setFields({ ...fields, name: value })} placeholder="Jordan Pearce" />}{<Field label="Email" value={fields.email} onChange={(value: string) => setFields({ ...fields, email: value })} placeholder="you@example.com" type="email" />}<Field label="Password" value={fields.password} onChange={(value: string) => setFields({ ...fields, password: value })} placeholder="At least 8 characters" type="password" />{error && <p className="auth-error">{error}</p>}<button className="primary auth-submit" disabled={busy}>{busy ? 'Working…' : mode === 'login' ? 'Sign in' : 'Create account'} <span>→</span></button><button type="button" className="text-button auth-switch" onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'Create an account' : 'Already have an account'} <span>→</span></button></form></div>
}

function ReportView({ report, title, standard, gardenRequirement, gardenAchieved, gardenClause, onBack }: any) { return <main className="report"><div className="report-head"><button className="back-link" onClick={onBack}>← Edit report</button><button className="secondary" onClick={() => window.print()}>Print / PDF</button></div><div className="report-title"><div className="eyebrow">TOWN PLANNING REPORT / DRAFT</div><h1>{title}</h1><p>Prepared for residential development assessment · Victoria</p></div><div className="report-grid"><section><h2>Project overview</h2><dl><dt>Address</dt><dd>{report.address || 'Not provided'}</dd><dt>Zone</dt><dd>{report.zone} · {report.zoneDescription}</dd><dt>Overlay(s)</dt><dd>{report.overlays || 'None identified'}</dd><dt>Local government</dt><dd>{report.lga || 'Not provided'}</dd></dl><h2>Development summary</h2><p className="body-copy">{report.summary || 'No summary has been entered yet.'}</p><h2>Site metrics</h2><div className="metrics"><Metric label="Site area" value={report.siteArea} /><Metric label="Frontage" value={report.frontage} suffix="m" /><Metric label="Site coverage" value={report.siteCoverage} /><Metric label="Garden area" value={report.gardenArea} /></div></section><aside><div className="report-note"><span className="eyebrow">GARDEN AREA</span><strong>{gardenAchieved || '—'}%</strong><p>{gardenRequirement ? `Minimum ${gardenRequirement}% required under Clause ${gardenClause}.` : 'Minimum requirement to be confirmed.'}</p></div><div className="report-note dark"><span className="eyebrow">ZONE STANDARDS</span><pre>{standard}</pre></div></aside></div><footer>PLAN / VIC · Working draft · {new Date().toLocaleDateString('en-AU')}</footer></main> }
function Metric({ label, value, suffix = 'm²' }: any) { return <div><span>{label}</span><strong>{value || '—'}{value && suffix}</strong></div> }

export default App
